name: MT5 Trading Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (to avoid 6h limit)

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install MetaTrader5
    - name: Run bot
      run: |
        python your_bot.py
      timeout-minutes: 300  # 5 hour limit
